"""Default settings for data processing and analysis.

Do not edit this file directly!

Instead, create a new configuration changing only the settings you need to
alter for your specific analysis.
"""

import importlib
import pathlib
import os
import logging
from typing import Optional, Union, Iterable, List, Tuple, Dict, Callable

import coloredlogs
from numpy.typing import ArrayLike
import matplotlib

import mne
from mne_bids import BIDSPath
import numpy as np

from mne_bids_pipeline._typing import PathLike, ArbitraryContrast, Literal
from mne_bids_pipeline._logging import gen_log_kwargs


###############################################################################
# Config parameters
# -----------------

from src.params import BIDS_PATH, PREPROC_PATH

interactive = True

study_name = 'Solaugh'
bids_root = BIDS_PATH
deriv_root = PREPROC_PATH

subjects = ['01'] #if 'all' include all subjects
sessions = ['recording']

task = 'LaughterActive'
runs = ['07']

find_flat_channels_meg = False
find_noisy_channels_meg = False
use_maxwell_filter = False
ch_types = ['mag']
eog_channels = ['EEG057', 'EEG058']
# ecg_channels = ['EEG059']
mf_cal_fname = None
l_freq = 1.
h_freq = 40.
resample_sfreq = 250

# Artifact correction.
spatial_filter = 'ica'
ica_max_iterations = 500
ica_l_freq = 1.
ica_n_components = 0.99
ica_reject_components = 'auto'

# Epochs
epochs_tmin = -1.5
epochs_tmax = 4.0
baseline = (None, 0)
contrasts = [('LaughReal', 'LaughPosed')]

# Conditions / events to consider when epoching
conditions = ['LaughReal', 'LaughPosed', 'Good', 'Bad']
event_repeated = 'drop'

# Noise estimation => select noise-session
process_empty_room = False
#noise_cov = 'emptyroom'

# Decoding
decode = False